version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres_oms
    restart: always
    environment:
      POSTGRES_DB: omsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"  
    volumes:
      - db-data:/var/lib/postgresql/data    
  pgadmin:
    container_name: pgadmin4_oms
    image: dpage/pgadmin4
    restart: always 
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  messagebus:  
    image: rabbitmq:3-management    
    container_name: rabbitmq_oms    
    restart: always
    ports:
      - "5672:5672"
      - "15762:15762"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"  
      RABBITMQ_DEFAULT_PASS: "guest" 
      RABBITMQ_ERLANG_COOKIE: 'secret code for cookie'
  vault:
    image: vault    
    container_name: vault_oms
    restart: always
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot    
    cap_add:
      - IPC_LOCK    
    ports:
      - 8200:8200
    volumes:
      - "vault_data:/vault/data"  
      - "vault_logs:/vault/logs"      
      - "vault_plugins:/vault/plugins"
  cache:
    image: redis:alpine
    restart: always       
    ports:
      - '6379:6379'    
    volumes: 
      - cache:/data
volumes:  
 db-data:
 pgadmin-data:
 vault_data:
 vault_logs:
 vault_configs:
 vault_plugins:
 cache: